[licenses]
# We want really high confidence when inferring licenses from text - value taken from cargo-deny's own deny.toml
confidence-threshold = 0.93
allow = ["Apache-2.0", "MIT", "Unicode-3.0", "Unlicense", "MPL-2.0"]
